Adding loop around final state transition to cut down failures

diff --git a/chef/cookbooks/provisioner/templates/default/crowbar_join.ubuntu.sh.erb b/chef/cookbooks/provisioner/templates/default/crowbar_join.ubuntu.sh.erb
--- a/chef/cookbooks/provisioner/templates/default/crowbar_join.ubuntu.sh.erb
+++ b/chef/cookbooks/provisioner/templates/default/crowbar_join.ubuntu.sh.erb
@@ -241,6 +241,9 @@ log_to time service ntp start
 service bluepill start
 
 # Transition to our final state
-post_state $HOSTNAME "$final_state"
+while ! post_state $HOSTNAME "$final_state"; do
+  echo "post_state $HOSTNAME \"$final_state\" failed! Retrying in 1s..."
+  sleep 1
+done
 
 echo "Done"
